### ISSUE TITLE
Executable in Release is not aligned with version in Master

### ISSUE THREAD

**Issue by miguelfreitas93** [cxpsemea/cxsast_consolidated_report#20]
Hi,

I've tried to execute the executable v1.3.1 and according to the documentation in master it requires an argument called --emailRecipients, but when I try to execute it, it ask for --receivers instead, since it was updated recently.

Is that possible to change the workflow for master, when there is a push, it generates automatically a new updated version to release ?

Thanks !

**Comment by hugomota** [comment]
This seems to be duplicated. Please check the #14
Closing this issue
